spring:
  datasource:
    url: ${DATABASE_URL} #jdbc:postgresql://localhost:5432/acaosocial-service
    username: ${DATABASE_USERNAME} #postgres
    password: ${DATABASE_PASSWORD} #dev123
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/b3social
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
server:
  port: 8081

springdoc:
  swagger-ui:
    path: /swagger-ui.html